### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nishant2019** [dvntstph/awx-openstack-automation#1]
For executing  **os_server_sample.yaml**   where is image: "auto-sync/ubuntu-bionic-18.04-amd64-server-20191021-disk1.img" needs to placed ???

**Comment by dvntstph** [comment]
This is the friendly name of an image in your Openstack Glance repository.

**Comment by nishant2019** [comment]
Thanks for reply, how can I upload image to Glance from internet directly and then provision it ?

**Comment by dvntstph** [comment]
You'll need a client workstation with the [Openstack CLI](https://docs.openstack.org/python-openstackclient/train/). A valid [Openstack RC](https://docs.openstack.org/newton/install-guide-ubuntu/keystone-openrc.html) file.

This example will import Ubuntu 18.04 image from cloud-images.ubuntu.com and upload it to glance and name the image bionic.

```
curl http://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img | \
    openstack image create --public --container-format=bare --disk-format=qcow2 \
    bionic 
```
